name: Print Secret and Delete PR

on:
  pull_request:
    types:
      - opened

jobs:
  print-secret-and-delete-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Secret to PR
        run: |
          echo "Secret Value: ${{ secrets.YOUR_SECRET_VARIABLE }}" > secret_output.txt
          echo "SECRET_OUTPUT=$(cat secret_output.txt)" >> $GITHUB_ENV

      - name: Comment on PR
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.SECRET_OUTPUT
            })

      - name: Wait for 30 seconds
        run: sleep 30

      - name: Delete PR
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.pulls.delete({
              pull_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            })
